# Generated by Django 3.0.6 on 2020-05-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('contact', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('address', models.TextField(max_length=150)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
    ]
