# Generated by Django 3.0.6 on 2020-06-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='contact',
            field=models.IntegerField(default='', max_length=15),
        ),
    ]
